/*
 * This header is generated by classdump-dyld 1.0
 * on Wednesday, May 16, 2018 at 2:01:14 PM Central European Summer Time
 * Operating System: Version 11.1.2 (Build 15B202)
 * Image Source: /System/Library/PrivateFrameworks/ControlCenterServices.framework/ControlCenterServices
 * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 */

#import "BSAbstractDefaultDomain.h"

@interface CCSControlCenterDefaults : BSAbstractDefaultDomain

@property (assign,nonatomic) NSUInteger presentationGesture;
@property (assign,nonatomic) NSUInteger userInvocationCount;
@property (assign,nonatomic) BOOL shouldEnablePrototypeFeatures;
@property (assign,nonatomic) BOOL shouldEnableInternalModules;
@property (assign,nonatomic) BOOL shouldEnableTigrisCarryUI;
+ (id)standardDefaults;
- (void)setShouldEnableInternalModules:(BOOL)arg1;
- (BOOL)shouldEnableInternalModules;
- (void)setPresentationGesture:(NSUInteger)arg1;
- (NSUInteger)presentationGesture;
- (void)setShouldEnablePrototypeFeatures:(BOOL)arg1;
- (BOOL)shouldEnablePrototypeFeatures;
- (void)setUserInvocationCount:(NSUInteger)arg1;
- (NSUInteger)userInvocationCount;
- (id)init;
- (void)_bindAndRegisterDefaults;
- (NSUInteger)_defaultPresentationGesture;
- (BOOL)shouldEnableTigrisCarryUI;
- (void)setShouldEnableTigrisCarryUI:(BOOL)arg1;
@end
