/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 16, 2018 at 2:01:14 PM Central European Summer Time
* Operating System: Version 11.1.2 (Build 15B202)
* Image Source: /System/Library/PrivateFrameworks/ControlCenterServices.framework/ControlCenterServices
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_source;
@class NSObject, NSHashTable, NSArray;

@interface CCSModuleSettingsProvider : NSObject {

	NSObject*<OS_dispatch_source> _configurationChangedSource;
	NSHashTable* _observers;
	NSArray* _orderedFixedModuleIdentifiers;
	NSArray* _orderedUserEnabledModuleIdentifiers;

}

@property (nonatomic,copy,readonly) NSArray * orderedFixedModuleIdentifiers;                    //@synthesize orderedFixedModuleIdentifiers=_orderedFixedModuleIdentifiers - In the implementation block
@property (nonatomic,copy,readonly) NSArray * orderedUserEnabledModuleIdentifiers;              //@synthesize orderedUserEnabledModuleIdentifiers=_orderedUserEnabledModuleIdentifiers - In the implementation block
+(void)initialize;
+(id)sharedProvider;
+(id)_defaultFixedModuleIdentifiers;
+(id)_configurationFileURL;
+(id)_configurationDirectoryURL;
+(id)_readOrderedIdentifiers;
+(id)_defaultUserEnabledModuleIdentifiers;
+(void)_writeOrderedIdentifiers:(id)arg1 ;
+(id)_defaultEnabledModuleOrder;
-(id)init;
-(void)dealloc;
-(void)addObserver:(id)arg1 ;
-(void)removeObserver:(id)arg1 ;
-(void)_saveSettings;
-(void)_startMonitoringConfigurationUpdates;
-(void)_stopMonitoringConfigurationUpdates;
-(void)_handleConfigurationFileUpdate;
-(void)setAndSaveOrderedUserEnabledModuleIdentifiers:(id)arg1 ;
-(void)_loadSettings;
-(NSArray *)orderedFixedModuleIdentifiers;
-(NSArray *)orderedUserEnabledModuleIdentifiers;
-(void)_runBlockOnListeners:(/*^block*/id)arg1 ;
@end

