/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, May 16, 2018 at 2:00:09 PM Central European Summer Time
* Operating System: Version 11.1.2 (Build 15B202)
* Image Source: /System/Library/PrivateFrameworks/ControlCenterUIKit.framework/ControlCenterUIKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <ControlCenterUIKit/ControlCenterUIKit-Structs.h>
#import <UIKit/UIVisualEffect.h>

@interface CCUIControlCenterVisualEffect : UIVisualEffect {

	long long _style;

}
+(id)effectWithStyle:(long long)arg1 ;
+(id)effectWithControlState:(unsigned long long)arg1 inContext:(long long)arg2 ;
+(id)_glyphOrTextOnPlatterOrBackgroundEffect;
+(id)_primaryHighlightedTextOnPlatterEffect;
+(id)_grayEffect;
+(id)_primaryRegularTextOnPlatterEffect;
+(id)_secondaryHighlightedTextOnPlatterEffect;
+(id)_secondaryRegularTextOnPlatterEffect;
+(id)_blackEffect;
+(id)_whiteEffect;
-(BOOL)isEqual:(id)arg1 ;
-(NSUInteger)hash;
-(long long)_style;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)initWithPrivateStyle:(long long)arg1 ;
-(id)contentsMultiplyColor;
-(id)effectConfig;
@end

