/*
 * This header is generated by classdump-dyld 1.0
 * on Thursday, January 25, 2018 at 11:22:03 PM Eastern European Standard Time
 * Operating System: Version 11.1.2 (Build 15B202)
 * Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
 * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 */


@protocol _UIBasicAnimationFactory <NSObject>
@optional
- (id)_timingFunctionForAnimation;
- (id)_timingFunctionForAnimationInView:(id)arg1 withKeyPath:(id)arg2;
- (BOOL)_shouldAnimateAdditivelyForView:(id)arg1 withKeyPath:(id)arg2;

@required
- (id)_basicAnimationForView:(id)arg1 withKeyPath:(id)arg2;

@end
