/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 25, 2018 at 11:29:33 PM Eastern European Standard Time
* Operating System: Version 11.1.2 (Build 15B202)
* Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <ControlCenterUI/ControlCenterUI-Structs.h>
#import "CCUIAnimationParameters.h"
#import "NSMutableCopying.h"

@protocol CCUIAnimationTimingFunctionDescription;
@class NSString;

@interface CCUICASpringAnimationParameters : NSObject <CCUIAnimationParameters, NSMutableCopying> {

	double _mass;
	double _stiffness;
	double _damping;
	id<CCUIAnimationTimingFunctionDescription> _timingFunction;

}

@property (nonatomic,readonly) double mass;                                                                 //@synthesize mass=_mass - In the implementation block
@property (nonatomic,readonly) double stiffness;                                                            //@synthesize stiffness=_stiffness - In the implementation block
@property (nonatomic,readonly) double damping;                                                              //@synthesize damping=_damping - In the implementation block
@property (nonatomic,copy,readonly) id<CCUIAnimationTimingFunctionDescription> timingFunction;              //@synthesize timingFunction=_timingFunction - In the implementation block
@property (readonly) NSUInteger hash;
@property (readonly) Class superclass;
@property (copy,readonly) NSString * description;
@property (copy,readonly) NSString * debugDescription;
-(id)init;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(NSString *)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id<CCUIAnimationTimingFunctionDescription>)timingFunction;
-(double)damping;
-(double)mass;
-(id)mutableCopyWithZone:(NSZone*)arg1 ;
-(double)stiffness;
-(id)_initWithAnimationParameters:(id)arg1 ;
@end
