/*
 * This header is generated by classdump-dyld 1.0
 * on Thursday, January 25, 2018 at 11:29:33 PM Eastern European Standard Time
 * Operating System: Version 11.1.2 (Build 15B202)
 * Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
 * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 */

#import <ControlCenterUI/ControlCenterUI-Structs.h>


@interface CCUIOverlayTransitionState : NSObject <NSCopying> {

	BOOL _interactive;
	NSUInteger _type;
	CGFloat _progress;
	CGFloat _presentationProgress;
	CGFloat _clampedPresentationProgress;
	CGFloat _nonZeroPresentationProgress;
	CGFloat _snappedPresentationProgress;

}

@property (nonatomic,readonly) NSUInteger type;					//@synthesize type=_type - In the implementation block
@property (nonatomic,readonly) CGFloat progress;					//@synthesize progress=_progress - In the implementation block
@property (getter=isInteractive,nonatomic,readonly) BOOL interactive;			//@synthesize interactive=_interactive - In the implementation block
@property (nonatomic,readonly) CGFloat presentationProgress;				//@synthesize presentationProgress=_presentationProgress - In the implementation block
@property (nonatomic,readonly) CGFloat clampedPresentationProgress;			//@synthesize clampedPresentationProgress=_clampedPresentationProgress - In the implementation block
@property (nonatomic,readonly) CGFloat nonZeroPresentationProgress;			//@synthesize nonZeroPresentationProgress=_nonZeroPresentationProgress - In the implementation block
@property (nonatomic,readonly) CGFloat snappedPresentationProgress;			//@synthesize snappedPresentationProgress=_snappedPresentationProgress - In the implementation block
+ (BOOL)isSignificantTransitionFrom:(id)arg1 to:(id)arg2;
+ (BOOL)isSignificantStatusBarTransitionFrom:(id)arg1 to:(id)arg2;
+ (id)stateWithType:(NSUInteger)arg1 interactive:(BOOL)arg2 progress:(CGFloat)arg3;
+ (id)fullyPresentedState;
+ (id)fullyDismissedState;
- (BOOL)isInteractive;
- (NSUInteger)type;
- (id)copyWithZone:(NSZone*)arg1;
- (CGFloat)progress;
- (CGFloat)snappedStatusBarPresentationProgress;
- (CGFloat)clampedPresentationProgress;
- (CGFloat)snappedPresentationProgress;
- (CGFloat)nonZeroPresentationProgress;
- (CGFloat)presentationProgress;
- (instancetype)_initWithType:(NSUInteger)arg1 interactive:(BOOL)arg2 progress:(CGFloat)arg3;
@end
