/*
 * This header is generated by classdump-dyld 1.0
 * on Thursday, January 25, 2018 at 11:29:33 PM Eastern European Standard Time
 * Operating System: Version 11.1.2 (Build 15B202)
 * Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
 * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 */


@protocol OS_dispatch_group;
@class NSObject;

@interface CCUIAnimationRunner : NSObject {

	NSObject<OS_dispatch_group>* _previousAnimationGroup;

}
+ (id)runner;
+ (void)_runCAAnimationsInBatch:(id)arg1 animationGroup:(id)arg2 completionHandler:(/*^block*/ id)arg3;
+ (void)_runC2AnimationsInBatch:(id)arg1 animationGroup:(id)arg2 completionHandler:(/*^block*/ id)arg3;
- (void)runAnimationBatch:(id)arg1 withCompletionBlock:(/*^block*/ id)arg2;
- (void)additivelyRunAnimationBatch:(id)arg1 withCompletionBlock:(/*^block*/ id)arg2;
@end
