/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 25, 2018 at 11:29:33 PM Eastern European Standard Time
* Operating System: Version 11.1.2 (Build 15B202)
* Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <ControlCenterUI/ControlCenterUI-Structs.h>
#import <ControlCenterUI/CCUIScrollView.h>

@protocol CCUILayoutViewLayoutSource;
@class CCUILayoutOptions;

@interface CCUILayoutView : CCUIScrollView {

	CCUILayoutOptions* _layoutOptions;
	id<CCUILayoutViewLayoutSource> _layoutSource;
	UIEdgeInsets _edgeInsets;

}

@property (assign,nonatomic) UIEdgeInsets edgeInsets;                                         //@synthesize edgeInsets=_edgeInsets - In the implementation block
@property (assign,nonatomic,weak) id<CCUILayoutViewLayoutSource> layoutSource;              //@synthesize layoutSource=_layoutSource - In the implementation block
-(void)setNeedsLayout;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(CGSize)intrinsicContentSize;
-(UIEdgeInsets)edgeInsets;
-(void)didAddSubview:(id)arg1 ;
-(void)willRemoveSubview:(id)arg1 ;
-(void)setEdgeInsets:(UIEdgeInsets)arg1 ;
-(void)setLayoutSource:(id<CCUILayoutViewLayoutSource>)arg1 ;
-(id)initWithFrame:(CGRect)arg1 layoutOptions:(id)arg2 ;
-(CGRect)frameForLayoutRect:(CCUILayoutRect)arg1 ;
-(CGRect)frameForSubview:(id)arg1 ;
-(void)iterateLayoutSubviewsWithBlock:(/*^block*/id)arg1 ;
-(id<CCUILayoutViewLayoutSource>)layoutSource;
-(id)subviewsToLayout;
@end

