/*
 * This header is generated by classdump-dyld 1.0
 * on Thursday, January 25, 2018 at 11:29:33 PM Eastern European Standard Time
 * Operating System: Version 11.1.2 (Build 15B202)
 * Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
 * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 */

#import <ControlCenterUI/ControlCenterUI-Structs.h>
#import <ControlCenterUI/CCUIC2AnimationParameters.h>

@interface CCUIMutableC2AnimationParameters : CCUIC2AnimationParameters

@property (assign,getter=isInteractive,nonatomic) BOOL interactive;
@property (assign,nonatomic) CGFloat tension;
@property (assign,nonatomic) CGFloat friction;
- (id)copyWithZone:(NSZone*)arg1;
- (void)setFriction:(CGFloat)arg1;
- (void)setInteractive:(BOOL)arg1;
- (void)setTension:(CGFloat)arg1;
@end
