/*
 * This header is generated by classdump-dyld 1.0
 * on Thursday, January 25, 2018 at 11:29:33 PM Eastern European Standard Time
 * Operating System: Version 11.1.2 (Build 15B202)
 * Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
 * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 */

#import "CCSModuleRepositoryObserver.h"
#import "CCUIContentModuleContextDelegate.h"

@protocol CCUIControlCenterSystemAgent, CCUIContentModuleContextDelegate;
@class CCSModuleRepository, NSMutableDictionary, NSHashTable, NSSet, NSArray, NSString;

@interface CCUIModuleInstanceManager : NSObject <CCSModuleRepositoryObserver, CCUIContentModuleContextDelegate> {

	id<CCUIControlCenterSystemAgent> _systemAgent;
	CCSModuleRepository* _repository;
	NSMutableDictionary* _moduleInstanceByIdentifier;
	NSHashTable* _observers;
	id<CCUIContentModuleContextDelegate> _contextDelegate;
	NSSet* _enabledModuleIdentifiers;

}

@property (nonatomic,weak) id<CCUIContentModuleContextDelegate> contextDelegate;		//@synthesize contextDelegate=_contextDelegate - In the implementation block
@property (nonatomic,copy) NSSet * enabledModuleIdentifiers;						//@synthesize enabledModuleIdentifiers=_enabledModuleIdentifiers - In the implementation block
@property (nonatomic,readonly) NSArray * moduleInstances;
@property (readonly) NSUInteger hash;
@property (readonly) Class superclass;
@property (copy,readonly) NSString * description;
@property (copy,readonly) NSString * debugDescription;
+ (instancetype)sharedInstance;
+ (void)initialize;
+ (void)setupSharedInstanceWithSystemAgent:(id)arg1;
- (void)addObserver:(id)arg1;
- (void)removeObserver:(id)arg1;
- (void)setEnabledModuleIdentifiers:(NSSet *)arg1;
- (NSArray *)moduleInstances;
- (instancetype)_initWithSystemAgent:(id)arg1 repository:(id)arg2;
- (void)_updateModuleInstances;
- (NSSet *)enabledModuleIdentifiers;
- (id)_instantiateModuleWithMetadata:(id)arg1;
- (void)_runBlockOnObservers:(/*^block*/ id)arg1;
- (id<CCUIContentModuleContextDelegate>)contextDelegate;
- (void)contentModuleContext:(id)arg1 enqueueStatusUpdate:(id)arg2;
- (void)requestExpandModuleForContentModuleContext:(id)arg1;
- (void)dismissExpandedViewForContentModuleContext:(id)arg1;
- (void)loadableModulesChangedForModuleRepository:(id)arg1;
- (void)setContextDelegate:(id<CCUIContentModuleContextDelegate>)arg1;
@end
