/*
 * This header is generated by classdump-dyld 1.0
 * on Thursday, January 25, 2018 at 11:29:33 PM Eastern European Standard Time
 * Operating System: Version 11.1.2 (Build 15B202)
 * Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
 * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 */

@class MTMaterialView, UIScrollView, UIView, CCUIModuleCollectionView, CCUIStatusLabelViewController, CCUIHeaderPocketView, UIStatusBar;


@protocol CCUIOverlayViewProvider <NSObject>
@property (nonatomic,readonly) MTMaterialView * overlayBackgroundView;
@property (nonatomic,readonly) UIScrollView * overlayScrollView;
@property (nonatomic,readonly) UIView * overlayContainerView;
@property (nonatomic,readonly) CCUIModuleCollectionView * overlayModuleCollectionView;
@property (nonatomic,readonly) CCUIStatusLabelViewController * overlayStatusLabelViewController;
@property (nonatomic,readonly) CCUIHeaderPocketView * overlayHeaderView;
@property (nonatomic,readonly) UIStatusBar * overlayLeadingStatusBar;
@required
- (UIScrollView *)overlayScrollView;
- (UIView *)overlayContainerView;
- (MTMaterialView *)overlayBackgroundView;
- (CCUIHeaderPocketView *)overlayHeaderView;
- (UIStatusBar *)overlayLeadingStatusBar;
- (CCUIStatusLabelViewController *)overlayStatusLabelViewController;
- (CCUIModuleCollectionView *)overlayModuleCollectionView;
- (void)setOverlayStatusBarHidden:(BOOL)arg1;

@end
