/*
 * This header is generated by classdump-dyld 1.0
 * on Wednesday, January 24, 2018 at 12:17:22 AM Eastern European Standard Time
 * Operating System: Version 11.1.2 (Build 15B202)
 * Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
 * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 */


@protocol CCUIModularControlCenterCardViewControllerDelegate <CCUIModularControlCenterViewControllerDelegate>
@optional
- (id)obscuringBackgroundViewForControlCenterViewController:(id)arg1;

@required
- (NSInteger)interfaceOrientationForControlCenterViewController:(id)arg1;
- (CGFloat)statusTextHeightForControlCenterViewController:(id)arg1;

@end
