/*
 * This header is generated by classdump-dyld 1.0
 * on Thursday, January 25, 2018 at 11:29:33 PM Eastern European Standard Time
 * Operating System: Version 11.1.2 (Build 15B202)
 * Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
 * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 */

#import <ControlCenterUI/ControlCenterUI-Structs.h>
#import "CCSModuleSettingsProviderObserver.h"

@class CCSModuleSettingsProvider, NSDictionary, NSHashTable, NSString;

@interface CCUIModuleSettingsManager : NSObject <CCSModuleSettingsProviderObserver> {

	CCSModuleSettingsProvider* _settingsProvider;
	NSDictionary* _settingsByIdentifier;
	NSHashTable* _observers;

}

@property (readonly) NSUInteger hash;
@property (readonly) Class superclass;
@property (copy,readonly) NSString * description;
@property (copy,readonly) NSString * debugDescription;
- (instancetype)init;
- (void)addObserver:(id)arg1;
- (void)removeObserver:(id)arg1;
- (id)orderedEnabledModuleIdentifiers;
- (id)sortModuleIdentifiers:(id)arg1 forInterfaceOrientation:(NSInteger)arg2;
- (id)moduleSettingsForModuleIdentifier:(id)arg1 prototypeSize:(CCUILayoutSize)arg2;
- (void)_loadSettings;
- (void)_runBlockOnListeners:(/*^block*/ id)arg1;
- (void)orderedEnabledModuleIdentifiersChangedForSettingsProvider:(id)arg1;
@end
