/*
 * This header is generated by classdump-dyld 1.0
 * on Thursday, January 25, 2018 at 11:29:33 PM Eastern European Standard Time
 * Operating System: Version 11.1.2 (Build 15B202)
 * Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
 * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 */

#import <ControlCenterUI/ControlCenterUI-Structs.h>
#import "CCUIAnimationParameters.h"


@class NSString;

@interface CCUIC2AnimationParameters : NSObject <CCUIAnimationParameters, NSMutableCopying> {

	BOOL _interactive;
	CGFloat _tension;
	CGFloat _friction;

}

@property (getter=isInteractive,nonatomic,readonly) BOOL interactive;			//@synthesize interactive=_interactive - In the implementation block
@property (nonatomic,readonly) CGFloat tension;						//@synthesize tension=_tension - In the implementation block
@property (nonatomic,readonly) CGFloat friction;					//@synthesize friction=_friction - In the implementation block
@property (readonly) NSUInteger hash;
@property (readonly) Class superclass;
@property (copy,readonly) NSString * description;
@property (copy,readonly) NSString * debugDescription;
- (instancetype)init;
- (BOOL)isEqual:(id)arg1;
- (NSUInteger)hash;
- (NSString *)description;
- (BOOL)isInteractive;
- (id)copyWithZone:(NSZone*)arg1;
- (CGFloat)friction;
- (id)mutableCopyWithZone:(NSZone*)arg1;
- (CGFloat)tension;
- (instancetype)_initWithAnimationParameters:(id)arg1;
@end
