/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 25, 2018 at 11:29:33 PM Eastern European Standard Time
* Operating System: Version 11.1.2 (Build 15B202)
* Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <ControlCenterUI/ControlCenterUI-Structs.h>
#import <UIKit/UIView.h>

@class MTMaterialView, NSString;

@interface CCUIContentModuleContentContainerView : UIView {

	BOOL _expanded;
	BOOL _moduleProvidesOwnPlatter;
	BOOL _clipsContentInCompactMode;
	MTMaterialView* _moduleMaterialView;
	NSString* _materialViewGroupName;

}

@property (assign,nonatomic) BOOL moduleProvidesOwnPlatter;                      //@synthesize moduleProvidesOwnPlatter=_moduleProvidesOwnPlatter - In the implementation block
@property (nonatomic,readonly) MTMaterialView * moduleMaterialView;              //@synthesize moduleMaterialView=_moduleMaterialView - In the implementation block
@property (nonatomic,copy) NSString * materialViewGroupName;                     //@synthesize materialViewGroupName=_materialViewGroupName - In the implementation block
@property (assign,nonatomic) BOOL clipsContentInCompactMode;                     //@synthesize clipsContentInCompactMode=_clipsContentInCompactMode - In the implementation block
-(id)init;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)addSubview:(id)arg1 ;
-(void)layoutSubviews;
-(void)_setContinuousCornerRadius:(double)arg1 ;
-(void)_transitionToExpandedMode:(BOOL)arg1 force:(BOOL)arg2 ;
-(void)_configureModuleMaterialViewIfNecessary;
-(BOOL)_isContentClippingRequiredForSubview:(id)arg1 ;
-(void)transitionToExpandedMode:(BOOL)arg1 ;
-(void)setModuleProvidesOwnPlatter:(BOOL)arg1 ;
-(MTMaterialView *)moduleMaterialView;
-(void)setMaterialViewGroupName:(NSString *)arg1 ;
-(BOOL)moduleProvidesOwnPlatter;
-(NSString *)materialViewGroupName;
-(BOOL)clipsContentInCompactMode;
-(void)setClipsContentInCompactMode:(BOOL)arg1 ;
@end

