/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 25, 2018 at 11:29:33 PM Eastern European Standard Time
* Operating System: Version 11.1.2 (Build 15B202)
* Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <ControlCenterUI/ControlCenterUI-Structs.h>
#import "NSCopying.h"

@interface CCUIModuleSettings : NSObject <NSCopying> {

	CCUILayoutSize _portraitLayoutSize;
	CCUILayoutSize _landscapeLayoutSize;

}
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(CCUILayoutSize)layoutSizeForInterfaceOrientation:(long long)arg1 ;
-(id)initWithPortraitLayoutSize:(CCUILayoutSize)arg1 landscapeLayoutSize:(CCUILayoutSize)arg2 ;
@end
