/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 25, 2018 at 11:29:33 PM Eastern European Standard Time
* Operating System: Version 11.1.2 (Build 15B202)
* Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <ControlCenterUI/ControlCenterUI-Structs.h>
#import "NSCopying.h"

@interface CCUIOverlayTransitionState : NSObject <NSCopying> {

	BOOL _interactive;
	unsigned long long _type;
	double _progress;
	double _presentationProgress;
	double _clampedPresentationProgress;
	double _nonZeroPresentationProgress;
	double _snappedPresentationProgress;

}

@property (nonatomic,readonly) unsigned long long type;                            //@synthesize type=_type - In the implementation block
@property (nonatomic,readonly) double progress;                                    //@synthesize progress=_progress - In the implementation block
@property (getter=isInteractive,nonatomic,readonly) BOOL interactive;              //@synthesize interactive=_interactive - In the implementation block
@property (nonatomic,readonly) double presentationProgress;                        //@synthesize presentationProgress=_presentationProgress - In the implementation block
@property (nonatomic,readonly) double clampedPresentationProgress;                 //@synthesize clampedPresentationProgress=_clampedPresentationProgress - In the implementation block
@property (nonatomic,readonly) double nonZeroPresentationProgress;                 //@synthesize nonZeroPresentationProgress=_nonZeroPresentationProgress - In the implementation block
@property (nonatomic,readonly) double snappedPresentationProgress;                 //@synthesize snappedPresentationProgress=_snappedPresentationProgress - In the implementation block
+(BOOL)isSignificantTransitionFrom:(id)arg1 to:(id)arg2 ;
+(BOOL)isSignificantStatusBarTransitionFrom:(id)arg1 to:(id)arg2 ;
+(id)stateWithType:(unsigned long long)arg1 interactive:(BOOL)arg2 progress:(double)arg3 ;
+(id)fullyPresentedState;
+(id)fullyDismissedState;
-(BOOL)isInteractive;
-(unsigned long long)type;
-(id)copyWithZone:(NSZone*)arg1 ;
-(double)progress;
-(double)snappedStatusBarPresentationProgress;
-(double)clampedPresentationProgress;
-(double)snappedPresentationProgress;
-(double)nonZeroPresentationProgress;
-(double)presentationProgress;
-(id)_initWithType:(unsigned long long)arg1 interactive:(BOOL)arg2 progress:(double)arg3 ;
@end
