/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 25, 2018 at 11:29:33 PM Eastern European Standard Time
* Operating System: Version 11.1.2 (Build 15B202)
* Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <ControlCenterUI/ControlCenterUI-Structs.h>
#import "CCUIAnimationTimingFunctionDescription.h"

@class NSString;

@interface CCUIAnimationCustomTimingFunctionParameters : NSObject <CCUIAnimationTimingFunctionDescription> {

	CGPoint _controlPoint1;
	CGPoint _controlPoint2;

}

@property (nonatomic,readonly) CGPoint controlPoint1;               //@synthesize controlPoint1=_controlPoint1 - In the implementation block
@property (nonatomic,readonly) CGPoint controlPoint2;               //@synthesize controlPoint2=_controlPoint2 - In the implementation block
@property (readonly) NSUInteger hash;
@property (readonly) Class superclass;
@property (copy,readonly) NSString * description;
@property (copy,readonly) NSString * debugDescription;
+(id)functionWithControlPoint1:(CGPoint)arg1 controlPoint2:(CGPoint)arg2 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(NSString *)description;
-(id)copyWithZone:(NSZone*)arg1 ;
-(CGPoint)controlPoint1;
-(CGPoint)controlPoint2;
-(id)_initWithControlPoint1:(CGPoint)arg1 controlPoint2:(CGPoint)arg2 ;
@end
