/*
 * This header is generated by classdump-dyld 1.0
 * on Thursday, January 25, 2018 at 11:29:33 PM Eastern European Standard Time
 * Operating System: Version 11.1.2 (Build 15B202)
 * Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
 * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 */

#import "CCUICAAnimationFactory.h"

@class CCUICASpringAnimationParameters, NSString;

@interface CCUICASpringAnimationFactory : NSObject <CCUICAAnimationFactory> {

	CCUICASpringAnimationParameters* _parameters;
	CGFloat _speed;

}

@property (readonly) NSUInteger hash;
@property (readonly) Class superclass;
@property (copy,readonly) NSString * description;
@property (copy,readonly) NSString * debugDescription;
@property (nonatomic,readonly) CGFloat animationDuration;
- (id)_basicAnimationForView:(id)arg1 withKeyPath:(id)arg2;
- (BOOL)_shouldAnimateAdditivelyForView:(id)arg1 withKeyPath:(id)arg2;
- (CGFloat)animationDuration;
- (id)_animation;
- (instancetype)initWithParameters:(id)arg1 speed:(CGFloat)arg2;
@end
