/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 25, 2018 at 11:29:33 PM Eastern European Standard Time
* Operating System: Version 11.1.2 (Build 15B202)
* Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <ControlCenterUI/ControlCenterUI-Structs.h>
#import "NSCopying.h"

@class UIStatusBarStyleRequest;

@interface CCUIStatusBarStyleSnapshot : NSObject <NSCopying> {

	BOOL _hidden;
	UIStatusBarStyleRequest* _activeStyleRequest;

}

@property (getter=isHidden,nonatomic,readonly) BOOL hidden;                                    //@synthesize hidden=_hidden - In the implementation block
@property (nonatomic,copy,readonly) UIStatusBarStyleRequest * activeStyleRequest;              //@synthesize activeStyleRequest=_activeStyleRequest - In the implementation block
-(BOOL)isHidden;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)initWithHidden:(BOOL)arg1 activeStyleRequest:(id)arg2 ;
-(UIStatusBarStyleRequest *)activeStyleRequest;
@end
