/*
 * This header is generated by classdump-dyld 1.0
 * on Thursday, January 25, 2018 at 11:29:33 PM Eastern European Standard Time
 * Operating System: Version 11.1.2 (Build 15B202)
 * Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
 * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 */

#import <ControlCenterUI/ControlCenterUI-Structs.h>


@protocol CCUIContentModule;
@class CCSModuleMetadata;

@interface CCUIModuleInstance : NSObject <NSCopying> {

	CCSModuleMetadata* _metadata;
	id<CCUIContentModule> _module;
	CCUILayoutSize _prototypeModuleSize;

}

@property (nonatomic,readonly) CCSModuleMetadata * metadata;			//@synthesize metadata=_metadata - In the implementation block
@property (nonatomic,readonly) id<CCUIContentModule> module;			//@synthesize module=_module - In the implementation block
@property (nonatomic,readonly) CCUILayoutSize prototypeModuleSize;		//@synthesize prototypeModuleSize=_prototypeModuleSize - In the implementation block
- (id<CCUIContentModule>)module;
- (id)copyWithZone:(NSZone*)arg1;
- (CCSModuleMetadata *)metadata;
- (CCUILayoutSize)prototypeModuleSize;
- (instancetype)initWithMetadata:(id)arg1 module:(id)arg2 prototypeModuleSize:(CCUILayoutSize)arg3;
@end
