/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 25, 2018 at 11:29:33 PM Eastern European Standard Time
* Operating System: Version 11.1.2 (Build 15B202)
* Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <ControlCenterUI/ControlCenterUI-Structs.h>
#import <UIKit/UIView.h>

@protocol CCUIStatusBarDelegate;
@class MTMaterialView, UIView, SBUIChevronView, CCUIStatusBar;

@interface CCUIHeaderPocketView : UIView {

	MTMaterialView* _headerBackgroundView;
	UIView* _headerLineView;
	SBUIChevronView* _headerChevronView;
	CCUIStatusBar* _statusBar;
	id<CCUIStatusBarDelegate> _statusBarDelegate;
	unsigned long long _mode;
	double _backgroundAlpha;
	double _contentAlpha;
	double _contentAlphaMultiplier;
	UIEdgeInsets _edgeInsets;
	CGAffineTransform _contentTransform;

}

@property (nonatomic,readonly) CGRect contentBounds; 
@property (nonatomic,readonly) CCUIStatusBar * statusBar;                                     //@synthesize statusBar=_statusBar - In the implementation block
@property (assign,nonatomic,weak) id<CCUIStatusBarDelegate> statusBarDelegate;              //@synthesize statusBarDelegate=_statusBarDelegate - In the implementation block
@property (assign,nonatomic) unsigned long long mode;                                         //@synthesize mode=_mode - In the implementation block
@property (assign,nonatomic) UIEdgeInsets edgeInsets;                                         //@synthesize edgeInsets=_edgeInsets - In the implementation block
@property (assign,nonatomic) double backgroundAlpha;                                          //@synthesize backgroundAlpha=_backgroundAlpha - In the implementation block
@property (assign,nonatomic) double contentAlpha;                                             //@synthesize contentAlpha=_contentAlpha - In the implementation block
@property (assign,nonatomic) double contentAlphaMultiplier;                                   //@synthesize contentAlphaMultiplier=_contentAlphaMultiplier - In the implementation block
@property (assign,nonatomic) CGAffineTransform contentTransform;                              //@synthesize contentTransform=_contentTransform - In the implementation block
@property (assign,nonatomic) unsigned long long chevronState; 
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(CCUIStatusBar *)statusBar;
-(UIEdgeInsets)edgeInsets;
-(unsigned long long)mode;
-(void)setEdgeInsets:(UIEdgeInsets)arg1 ;
-(void)setMode:(unsigned long long)arg1 ;
-(void)setBackgroundAlpha:(double)arg1 ;
-(void)setContentAlpha:(double)arg1 ;
-(double)backgroundAlpha;
-(CGRect)contentBounds;
-(double)contentAlpha;
-(void)setContentTransform:(CGAffineTransform)arg1 ;
-(void)setChevronState:(unsigned long long)arg1 ;
-(void)setContentAlphaMultiplier:(double)arg1 ;
-(CGAffineTransform)contentTransform;
-(id<CCUIStatusBarDelegate>)statusBarDelegate;
-(void)_updateContentTransform;
-(void)setStatusBarDelegate:(id<CCUIStatusBarDelegate>)arg1 ;
-(unsigned long long)chevronState;
-(double)contentAlphaMultiplier;
-(void)_updateAlpha;
@end

