/*
 * This header is generated by classdump-dyld 1.0
 * on Wednesday, January 24, 2018 at 12:17:23 AM Eastern European Standard Time
 * Operating System: Version 11.1.2 (Build 15B202)
 * Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
 * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 */

@class CCUIStatusBarStyleSnapshot;


@protocol CCUIHostStatusBarStyleProvider <NSObject>
@property (nonatomic,copy,readonly) CCUIStatusBarStyleSnapshot * hostStatusBarStyle;
@required
- (CCUIStatusBarStyleSnapshot *)hostStatusBarStyle;

@end
