/*
 * This header is generated by classdump-dyld 1.0
 * on Thursday, January 25, 2018 at 11:29:33 PM Eastern European Standard Time
 * Operating System: Version 11.1.2 (Build 15B202)
 * Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
 * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 */

#import <ControlCenterUI/ControlCenterUI-Structs.h>
#import <UIKit/UIView.h>

@protocol CCUIStatusBarDelegate;
@class MTMaterialView, UIView, SBUIChevronView, CCUIStatusBar;

@interface CCUIHeaderPocketView : UIView {

	MTMaterialView* _headerBackgroundView;
	UIView* _headerLineView;
	SBUIChevronView* _headerChevronView;
	CCUIStatusBar* _statusBar;
	id<CCUIStatusBarDelegate> _statusBarDelegate;
	NSUInteger _mode;
	CGFloat _backgroundAlpha;
	CGFloat _contentAlpha;
	CGFloat _contentAlphaMultiplier;
	UIEdgeInsets _edgeInsets;
	CGAffineTransform _contentTransform;

}

@property (nonatomic,readonly) CGRect contentBounds;
@property (nonatomic,readonly) CCUIStatusBar * statusBar;					//@synthesize statusBar=_statusBar - In the implementation block
@property (nonatomic,weak) id<CCUIStatusBarDelegate> statusBarDelegate;			//@synthesize statusBarDelegate=_statusBarDelegate - In the implementation block
@property (assign,nonatomic) NSUInteger mode;						//@synthesize mode=_mode - In the implementation block
@property (assign,nonatomic) UIEdgeInsets edgeInsets;						//@synthesize edgeInsets=_edgeInsets - In the implementation block
@property (assign,nonatomic) CGFloat backgroundAlpha;						//@synthesize backgroundAlpha=_backgroundAlpha - In the implementation block
@property (assign,nonatomic) CGFloat contentAlpha;						//@synthesize contentAlpha=_contentAlpha - In the implementation block
@property (assign,nonatomic) CGFloat contentAlphaMultiplier;					//@synthesize contentAlphaMultiplier=_contentAlphaMultiplier - In the implementation block
@property (assign,nonatomic) CGAffineTransform contentTransform;				//@synthesize contentTransform=_contentTransform - In the implementation block
@property (assign,nonatomic) NSUInteger chevronState;
- (instancetype)initWithFrame:(CGRect)arg1;
- (void)layoutSubviews;
- (CCUIStatusBar *)statusBar;
- (UIEdgeInsets)edgeInsets;
- (NSUInteger)mode;
- (void)setEdgeInsets:(UIEdgeInsets)arg1;
- (void)setMode:(NSUInteger)arg1;
- (void)setBackgroundAlpha:(CGFloat)arg1;
- (void)setContentAlpha:(CGFloat)arg1;
- (CGFloat)backgroundAlpha;
- (CGRect)contentBounds;
- (CGFloat)contentAlpha;
- (void)setContentTransform:(CGAffineTransform)arg1;
- (void)setChevronState:(NSUInteger)arg1;
- (void)setContentAlphaMultiplier:(CGFloat)arg1;
- (CGAffineTransform)contentTransform;
- (id<CCUIStatusBarDelegate>)statusBarDelegate;
- (void)_updateContentTransform;
- (void)setStatusBarDelegate:(id<CCUIStatusBarDelegate>)arg1;
- (NSUInteger)chevronState;
- (CGFloat)contentAlphaMultiplier;
- (void)_updateAlpha;
@end
