/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 25, 2018 at 11:29:33 PM Eastern European Standard Time
* Operating System: Version 11.1.2 (Build 15B202)
* Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <ControlCenterUI/ControlCenterUI-Structs.h>
#import <UIKit/UIView.h>

@protocol CCUIStatusBarDelegate;
@class UIStatusBar, UIStatusBarStyleRequest;

@interface CCUIStatusBar : UIView {

	UIStatusBar* _compactTrailingStatusBar;
	UIStatusBar* _extendedLeadingStatusBar;
	UIStatusBar* _extendedTrailingStatusBar;
	id<CCUIStatusBarDelegate> _delegate;
	unsigned long long _leadingState;
	unsigned long long _trailingState;
	UIEdgeInsets _compactEdgeInsets;
	UIEdgeInsets _expandedEdgeInsets;

}

@property (nonatomic,copy,readonly) UIStatusBarStyleRequest * compactStyleRequest; 
@property (assign,nonatomic,weak) id<CCUIStatusBarDelegate> delegate;                         //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) unsigned long long leadingState;                                   //@synthesize leadingState=_leadingState - In the implementation block
@property (assign,nonatomic) unsigned long long trailingState;                                  //@synthesize trailingState=_trailingState - In the implementation block
@property (assign,nonatomic) UIEdgeInsets compactEdgeInsets;                                    //@synthesize compactEdgeInsets=_compactEdgeInsets - In the implementation block
@property (assign,nonatomic) UIEdgeInsets expandedEdgeInsets;                                   //@synthesize expandedEdgeInsets=_expandedEdgeInsets - In the implementation block
@property (assign,nonatomic) double leadingAlpha; 
@property (assign,nonatomic) double compactTrailingAlpha; 
@property (assign,nonatomic) double expandedTrailingAlpha; 
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(id<CCUIStatusBarDelegate>)delegate;
-(void)setDelegate:(id<CCUIStatusBarDelegate>)arg1 ;
-(id)hitTest:(CGPoint)arg1 withEvent:(id)arg2 ;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(CGSize)intrinsicContentSize;
-(void)setCompactEdgeInsets:(UIEdgeInsets)arg1 ;
-(void)setExpandedEdgeInsets:(UIEdgeInsets)arg1 ;
-(void)setLeadingState:(unsigned long long)arg1 ;
-(void)setTrailingState:(unsigned long long)arg1 ;
-(void)setCompactTrailingAlpha:(double)arg1 ;
-(void)setLeadingAlpha:(double)arg1 ;
-(void)setExpandedTrailingAlpha:(double)arg1 ;
-(void)controlCenterApplyPrimaryContentShadow;
-(UIStatusBarStyleRequest *)compactStyleRequest;
-(void)_updateCompactTrailingStatusBarStyleRequest;
-(unsigned long long)leadingState;
-(unsigned long long)trailingState;
-(double)leadingAlpha;
-(double)compactTrailingAlpha;
-(double)expandedTrailingAlpha;
-(UIEdgeInsets)compactEdgeInsets;
-(UIEdgeInsets)expandedEdgeInsets;
@end

