/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 25, 2018 at 11:29:33 PM Eastern European Standard Time
* Operating System: Version 11.1.2 (Build 15B202)
* Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <BaseBoard/BSAbstractDefaultDomain.h>

@interface CCUIControlCenterDefaults : BSAbstractDefaultDomain

@property (nonatomic,readonly) BOOL shouldAlwaysBeEnabled; 
@property (nonatomic,readonly) BOOL shouldExcludeControlCenterFromStatusBarOverrides; 
@property (assign,nonatomic) BOOL hasForceTouchedToExpandModule; 
@property (assign,nonatomic) BOOL hasLongPressedToExpandModule; 
+(id)standardDefaults;
-(void)setShouldAlwaysBeEnabled:(BOOL)arg1 ;
-(BOOL)shouldAlwaysBeEnabled;
-(void)setHasForceTouchedToExpandModule:(BOOL)arg1 ;
-(BOOL)hasForceTouchedToExpandModule;
-(void)setShouldExcludeControlCenterFromStatusBarOverrides:(BOOL)arg1 ;
-(BOOL)shouldExcludeControlCenterFromStatusBarOverrides;
-(void)setHasLongPressedToExpandModule:(BOOL)arg1 ;
-(BOOL)hasLongPressedToExpandModule;
-(id)init;
-(void)_bindAndRegisterDefaults;
@end

