/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 25, 2018 at 11:29:33 PM Eastern European Standard Time
* Operating System: Version 11.1.2 (Build 15B202)
* Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <ControlCenterUI/ControlCenterUI-Structs.h>
#import <UIKit/UIViewController.h>
#import "CCUIModuleCollectionViewControllerDelegate.h"
#import "CCUIContentModuleContextDelegate.h"
#import "CCUIModuleInstanceManagerObserver.h"

@protocol CCUIModularControlCenterViewControllerDelegate;
@class CCUIModuleInstanceManager, CCUIStatusLabelViewController, CCUIModuleCollectionViewController, NSString;

@interface CCUIModularControlCenterViewController : UIViewController <CCUIModuleCollectionViewControllerDelegate, CCUIContentModuleContextDelegate, CCUIModuleInstanceManagerObserver> {

	CCUIModuleInstanceManager* _moduleManager;
	BOOL _active;
	BOOL _hostedInTestApp;
	id<CCUIModularControlCenterViewControllerDelegate> _delegate;
	CCUIModuleInstanceManager* _moduleInstanceManager;
	CCUIStatusLabelViewController* _statusLabelViewController;

}

@property (nonatomic,readonly) CCUIModuleInstanceManager * moduleInstanceManager;                                //@synthesize moduleInstanceManager=_moduleInstanceManager - In the implementation block
@property (nonatomic,readonly) CCUIStatusLabelViewController * statusLabelViewController;                        //@synthesize statusLabelViewController=_statusLabelViewController - In the implementation block
@property (nonatomic,readonly) CCUIModuleCollectionViewController * moduleCollectionViewController;
@property (assign,getter=isHostedInTestApp,nonatomic) BOOL hostedInTestApp;                                      //@synthesize hostedInTestApp=_hostedInTestApp - In the implementation block
@property (nonatomic,readonly) unsigned long long moduleRowCount;
@property (assign,nonatomic,weak) id<CCUIModularControlCenterViewControllerDelegate> delegate;                 //@synthesize delegate=_delegate - In the implementation block
@property (readonly) NSUInteger hash;
@property (readonly) Class superclass;
@property (copy,readonly) NSString * description;
@property (copy,readonly) NSString * debugDescription;
+(id)_sharedCollectionViewController;
-(id<CCUIModularControlCenterViewControllerDelegate>)delegate;
-(void)setDelegate:(id<CCUIModularControlCenterViewControllerDelegate>)arg1 ;
-(long long)_interfaceOrientation;
-(void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
-(CGSize)preferredContentSize;
-(void)viewDidLoad;
-(BOOL)shouldAutomaticallyForwardAppearanceMethods;
-(void)_resignActive;
-(BOOL)canDismissPresentedContent;
-(void)dismissPresentedContentAnimated:(BOOL)arg1 completion:(/*^block*/id)arg2 ;
-(long long)interfaceOrientationForModuleCollectionViewController:(id)arg1 ;
-(void)moduleCollectionViewController:(id)arg1 didBeginInteractionWithModule:(id)arg2 ;
-(void)moduleCollectionViewController:(id)arg1 didFinishInteractionWithModule:(id)arg2 ;
-(void)moduleCollectionViewController:(id)arg1 willOpenExpandedModule:(id)arg2 ;
-(void)moduleCollectionViewController:(id)arg1 didOpenExpandedModule:(id)arg2 ;
-(void)moduleCollectionViewController:(id)arg1 willCloseExpandedModule:(id)arg2 ;
-(void)moduleCollectionViewController:(id)arg1 didCloseExpandedModule:(id)arg2 ;
-(id)obscuringBackgroundViewForModuleCollectionViewController:(id)arg1 ;
-(void)moduleCollectionViewController:(id)arg1 didAddModuleContainerViewController:(id)arg2 ;
-(void)moduleCollectionViewController:(id)arg1 willRemoveModuleContainerViewController:(id)arg2 ;
-(void)moduleInstancesChangedForModuleInstanceManager:(id)arg1 ;
-(void)expandModuleWithIdentifier:(id)arg1 ;
-(void)dismissExpandedModuleAnimated:(BOOL)arg1 completion:(/*^block*/id)arg2 ;
-(void)contentModuleContext:(id)arg1 enqueueStatusUpdate:(id)arg2 ;
-(void)requestExpandModuleForContentModuleContext:(id)arg1 ;
-(void)dismissExpandedViewForContentModuleContext:(id)arg1 ;
-(id)initWithSystemAgent:(id)arg1 ;
-(CCUIModuleCollectionViewController *)moduleCollectionViewController;
-(void)dismissPresentedContentWithCompletionHandler:(/*^block*/id)arg1 ;
-(void)_reparentCollectionViewController;
-(void)_reparent;
-(id)_safeStatusLabelViewContainerView;
-(CCUIStatusLabelViewController *)statusLabelViewController;
-(id)_statusLabelViewContainerView;
-(id)_moduleCollectionViewContainerView;
-(id)_safeModuleCollectionViewContainerView;
-(unsigned long long)moduleRowCount;
-(void)closeCurrentModuleWithCompletionHandler:(/*^block*/id)arg1 ;
-(void)dismissPresentedContent;
-(void)_reparentAndBecomeActive;
-(id)interactionHighlightContainerViewForModuleCollectionViewController:(id)arg1 ;
-(CCUIModuleInstanceManager *)moduleInstanceManager;
-(BOOL)isHostedInTestApp;
-(void)setHostedInTestApp:(BOOL)arg1 ;
@end
