/*
 * This header is generated by classdump-dyld 1.0
 * on Thursday, January 25, 2018 at 11:29:33 PM Eastern European Standard Time
 * Operating System: Version 11.1.2 (Build 15B202)
 * Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
 * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 */

#import <ControlCenterUI/ControlCenterUI-Structs.h>



@interface CCUILayoutOptions : NSObject <NSCopying, NSMutableCopying> {

	CGFloat _itemEdgeSize;
	CGFloat _itemSpacing;

}

@property (nonatomic,readonly) CGFloat itemEdgeSize;			//@synthesize itemEdgeSize=_itemEdgeSize - In the implementation block
@property (nonatomic,readonly) CGFloat itemSpacing;			//@synthesize itemSpacing=_itemSpacing - In the implementation block
- (instancetype)init;
- (BOOL)isEqual:(id)arg1;
- (NSUInteger)hash;
- (id)description;
- (id)copyWithZone:(NSZone*)arg1;
- (CGFloat)itemSpacing;
- (id)mutableCopyWithZone:(NSZone*)arg1;
- (instancetype)_initWithLayoutOptions:(id)arg1;
- (CGFloat)itemEdgeSize;
@end
