/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 25, 2018 at 11:29:33 PM Eastern European Standard Time
* Operating System: Version 11.1.2 (Build 15B202)
* Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <ControlCenterUI/ControlCenterUI-Structs.h>
#import <UIKit/UIViewController.h>

@protocol CCUIStatusLabelViewControllerDelegate;
@class CCUIStatusUpdateQueue, NSArray, NSTimer;

@interface CCUIStatusLabelViewController : UIViewController {

	CCUIStatusUpdateQueue* _updateQueue;
	NSArray* _statusLabels;
	unsigned long long _currentStatusLabelIndex;
	unsigned long long _presentationState;
	NSTimer* _presentationTimer;
	id<CCUIStatusLabelViewControllerDelegate> _delegate;

}

@property (assign,nonatomic,weak) id<CCUIStatusLabelViewControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) UIEdgeInsets edgeInsets; 
@property (assign,nonatomic) unsigned long long verticalAlignment; 
-(id<CCUIStatusLabelViewControllerDelegate>)delegate;
-(void)setDelegate:(id<CCUIStatusLabelViewControllerDelegate>)arg1 ;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(UIEdgeInsets)edgeInsets;
-(void)viewWillLayoutSubviews;
-(void)viewDidLoad;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)viewDidDisappear:(BOOL)arg1 ;
-(void)setEdgeInsets:(UIEdgeInsets)arg1 ;
-(unsigned long long)verticalAlignment;
-(void)setVerticalAlignment:(unsigned long long)arg1 ;
-(void)enqueueStatusUpdate:(id)arg1 forIdentifier:(id)arg2 ;
-(void)_advancePresentationState;
-(void)_resetPresentationStateAnimated:(BOOL)arg1 ;
-(void)_fadeOutStatusLabel:(id)arg1 ;
-(void)_notifyDelegateDidFinishStatusUpdates;
-(unsigned long long)_advancePresentationStateFromReady;
-(unsigned long long)_advancePresentationStateFromFadeIn;
-(unsigned long long)_advancePresentationStateFromPresenting;
-(unsigned long long)_advancePresentationStateFromFadeOut;
-(void)_notifyDelegateWillBeginStatusUpdates;
-(void)_fadeInStatusLabel:(id)arg1 ;
@end

