/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 25, 2018 at 11:29:33 PM Eastern European Standard Time
* Operating System: Version 11.1.2 (Build 15B202)
* Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol CCUIContentModuleContextDelegate <NSObject>
@required
-(void)contentModuleContext:(id)arg1 enqueueStatusUpdate:(id)arg2;
-(void)requestExpandModuleForContentModuleContext:(id)arg1;
-(void)dismissExpandedViewForContentModuleContext:(id)arg1;

@end

