/*
 * This header is generated by classdump-dyld 1.0
 * on Thursday, January 25, 2018 at 11:29:33 PM Eastern European Standard Time
 * Operating System: Version 11.1.2 (Build 15B202)
 * Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
 * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 */

#import <ControlCenterUI/ControlCenterUI-Structs.h>
#import <UIKit/UIGestureRecognizer.h>

@class UITouch, NSTimer;

@interface CCUIFlickGestureRecognizer : UIGestureRecognizer {

	UITouch* _touch;
	NSTimer* _timeoutTimer;
	CGFloat _initialTouchTimestamp;
	CGPoint _initialTouchLocation;
	BOOL _latched;
	CGFloat _maximumFlickTime;
	CGFloat _minimumFlickVelocity;
	NSUInteger _allowedFlickDirections;

}

@property (assign,nonatomic) CGFloat maximumFlickTime;					//@synthesize maximumFlickTime=_maximumFlickTime - In the implementation block
@property (assign,nonatomic) CGFloat minimumFlickVelocity;				//@synthesize minimumFlickVelocity=_minimumFlickVelocity - In the implementation block
@property (assign,nonatomic) NSUInteger allowedFlickDirections;			//@synthesize allowedFlickDirections=_allowedFlickDirections - In the implementation block
- (instancetype)initWithTarget:(id)arg1 action:(SEL)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)reset;
- (void)setAllowedFlickDirections:(NSUInteger)arg1;
- (NSUInteger)allowedFlickDirections;
- (void)setMaximumFlickTime:(CGFloat)arg1;
- (void)setMinimumFlickVelocity:(CGFloat)arg1;
- (CGFloat)minimumFlickVelocity;
- (void)_beginFlickWithTouch:(id)arg1;
- (BOOL)_validateFlickWithTouch:(id)arg1;
- (CGFloat)maximumFlickTime;
- (void)_evaluateFlickAtTimeout;
@end
