/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 25, 2018 at 11:29:33 PM Eastern European Standard Time
* Operating System: Version 11.1.2 (Build 15B202)
* Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <ControlCenterUI/ControlCenterUI-Structs.h>
#import <UIKit/UIViewController.h>
#import "CCUIModuleInstanceManagerObserver.h"
#import "CCUIModuleSettingsManagerObserver.h"
#import "CCUILayoutViewLayoutSource.h"
#import "CCUIContentModuleContainerViewControllerDelegate.h"
#import "CCUISafeAppearancePropagationProvider.h"

@protocol OS_dispatch_group, CCUIModuleCollectionViewControllerDelegate;
@class NSArray, CCUIModuleInstanceManager, CCUIModuleSettingsManager, CCUIControlCenterPositionProvider, CCUILayoutOptions, NSDictionary, NSHashTable, NSObject, CCUIExpandedModuleBackgroundView, CCUIModuleCollectionView, NSString;

@interface CCUIModuleCollectionViewController : UIViewController <CCUIModuleInstanceManagerObserver, CCUIModuleSettingsManagerObserver, CCUILayoutViewLayoutSource, CCUIContentModuleContainerViewControllerDelegate, CCUISafeAppearancePropagationProvider> {

	CCUIModuleInstanceManager* _moduleManager;
	CCUIModuleSettingsManager* _settingsManager;
	CCUIControlCenterPositionProvider* _portraitPositionProvider;
	CCUIControlCenterPositionProvider* _landscapePositionProvider;
	CCUILayoutOptions* _layoutOptions;
	NSDictionary* _moduleViewControllerByIdentifier;
	NSDictionary* _moduleContainerViewByIdentifier;
	NSHashTable* _currentModules;
	NSHashTable* _expandedModules;
	NSObject*<OS_dispatch_group> _moduleCloseDispatchGroup;
	CCUIExpandedModuleBackgroundView* _sharedExpandedModuleBackgroundView;
	id<CCUIModuleCollectionViewControllerDelegate> _delegate;

}

@property (nonatomic,readonly) unsigned long long expandedModuleCount;
@property (nonatomic,retain) CCUIModuleCollectionView * moduleCollectionView;
@property (assign,nonatomic,weak) id<CCUIModuleCollectionViewControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) NSUInteger hash;
@property (readonly) Class superclass;
@property (copy,readonly) NSString * description;
@property (copy,readonly) NSString * debugDescription;
@property (nonatomic,readonly) NSArray * childViewControllersForAppearancePropagation;
-(id<CCUIModuleCollectionViewControllerDelegate>)delegate;
-(void)setDelegate:(id<CCUIModuleCollectionViewControllerDelegate>)arg1 ;
-(void)loadView;
-(long long)_interfaceOrientation;
-(CGSize)sizeForChildContentContainer:(id)arg1 withParentContainerSize:(CGSize)arg2 ;
-(CGSize)preferredContentSize;
-(void)viewDidLoad;
-(BOOL)shouldAutomaticallyForwardAppearanceMethods;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)viewDidDisappear:(BOOL)arg1 ;
-(void)willResignActive;
-(void)willBecomeActive;
-(void)dismissPresentedContentAnimated:(BOOL)arg1 completion:(/*^block*/id)arg2 ;
-(id)_currentLayoutOptions;
-(void)_updateEnabledModuleIdentifiers;
-(void)setModuleCollectionView:(CCUIModuleCollectionView *)arg1 ;
-(void)_refreshPositionProviders;
-(void)_populateModuleViewControllers;
-(CCUIModuleCollectionView *)moduleCollectionView;
-(id)_activePositionProvider;
-(id)_positionProviderForInterfaceOrientation:(long long)arg1 ;
-(void)_updateModuleControllers;
-(BOOL)_shouldApplyBackgroundEffects;
-(id)_moduleInstances;
-(id)_setupAndAddModuleViewControllerToHierarchy:(id)arg1 ;
-(void)_removeAndTearDownModuleViewControllerFromHierarchy:(id)arg1 ;
-(id)_sizesForModuleIdentifiers:(id)arg1 moduleInstanceByIdentifier:(id)arg2 interfaceOrientation:(long long)arg3 ;
-(void)moduleInstancesChangedForModuleInstanceManager:(id)arg1 ;
-(void)orderedEnabledModuleIdentifiersChangedForSettingsManager:(id)arg1 ;
-(CCUILayoutSize)layoutSizeForLayoutView:(id)arg1 ;
-(CCUILayoutRect)layoutView:(id)arg1 layoutRectForSubview:(id)arg2 ;
-(CGRect)compactModeFrameForContentModuleContainerViewController:(id)arg1 ;
-(BOOL)contentModuleContainerViewController:(id)arg1 canBeginInteractionWithModule:(id)arg2 ;
-(void)contentModuleContainerViewController:(id)arg1 didBeginInteractionWithModule:(id)arg2 ;
-(void)contentModuleContainerViewController:(id)arg1 didFinishInteractionWithModule:(id)arg2 ;
-(void)contentModuleContainerViewController:(id)arg1 willOpenExpandedModule:(id)arg2 ;
-(void)contentModuleContainerViewController:(id)arg1 didOpenExpandedModule:(id)arg2 ;
-(void)contentModuleContainerViewController:(id)arg1 willCloseExpandedModule:(id)arg2 ;
-(void)contentModuleContainerViewController:(id)arg1 didCloseExpandedModule:(id)arg2 ;
-(BOOL)shouldApplyBackgroundEffectsForContentModuleContainerViewController:(id)arg1 ;
-(id)backgroundViewForContentModuleContainerViewController:(id)arg1 ;
-(NSArray *)childViewControllersForAppearancePropagation;
-(id)initWithModuleInstanceManager:(id)arg1 ;
-(unsigned long long)expandedModuleCount;
-(void)expandModuleWithIdentifier:(id)arg1 ;
-(void)dismissExpandedModuleAnimated:(BOOL)arg1 completion:(/*^block*/id)arg2 ;
-(BOOL)isModuleExpandedForIdentifier:(id)arg1 ;
-(BOOL)isAtMaxHeight;
-(id)relevantSnapHeightsForOrientation:(long long)arg1 ;
-(id)queryAllTopLevelBlockingGestureRecognizers;
@end
