/*
 * This header is generated by classdump-dyld 1.0
 * on Thursday, January 25, 2018 at 11:29:33 PM Eastern European Standard Time
 * Operating System: Version 11.1.2 (Build 15B202)
 * Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
 * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 */

#import "_UIPreviewInteractionViewControllerTransition.h"

@class CCUIContentModuleContainerViewController, NSString;

@interface CCUIContentModuleContainerTransition : NSObject <_UIPreviewInteractionViewControllerTransition> {

	BOOL _appearanceTransition;
	CCUIContentModuleContainerViewController* _viewController;

}

@property (nonatomic,weak) CCUIContentModuleContainerViewController * viewController;			//@synthesize viewController=_viewController - In the implementation block
@property (assign,getter=isAppearanceTransition,nonatomic) BOOL appearanceTransition;				//@synthesize appearanceTransition=_appearanceTransition - In the implementation block
@property (readonly) NSUInteger hash;
@property (readonly) Class superclass;
@property (copy,readonly) NSString * description;
@property (copy,readonly) NSString * debugDescription;
- (void)setViewController:(CCUIContentModuleContainerViewController *)arg1;
- (CCUIContentModuleContainerViewController *)viewController;
- (void)setAppearanceTransition:(BOOL)arg1;
- (void)prepareTransitionFromView:(id)arg1 toView:(id)arg2 containerView:(id)arg3;
- (void)performTransitionFromView:(id)arg1 toView:(id)arg2 containerView:(id)arg3;
- (void)transitionDidEnd:(BOOL)arg1;
- (BOOL)isAppearanceTransition;
@end
