/*
* This header is generated by classdump-dyld 1.0
* on Thursday, January 25, 2018 at 11:29:33 PM Eastern European Standard Time
* Operating System: Version 11.1.2 (Build 15B202)
* Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol CCUIOverlayFlickGestureBehavior <NSObject>
@property (nonatomic,readonly) double dismissalFlickMaximumTime; 
@property (nonatomic,readonly) double dismissalFlickMinimumVelocity; 
@property (nonatomic,readonly) unsigned long long dismissalFlickAllowedDirections; 
@required
-(double)dismissalFlickMaximumTime;
-(double)dismissalFlickMinimumVelocity;
-(unsigned long long)dismissalFlickAllowedDirections;

@end

