/*
 * This header is generated by classdump-dyld 1.0
 * on Thursday, January 25, 2018 at 11:29:33 PM Eastern European Standard Time
 * Operating System: Version 11.1.2 (Build 15B202)
 * Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
 * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 */


#import <ControlCenterUI/ControlCenterUI-Structs.h>
@class NSArray, NSDictionary;

@interface CCUIControlCenterPositionProvider : NSObject {

	NSArray* _packingRules;
	NSDictionary* _rectByIdentifier;
	CCUILayoutSize _layoutSize;

}

@property (nonatomic,readonly) CCUILayoutSize layoutSize;			//@synthesize layoutSize=_layoutSize - In the implementation block
@property (nonatomic,readonly) CCUILayoutSize maximumLayoutSize;
- (CCUILayoutSize)layoutSize;
- (id)_generateRectByIdentifierWithOrderedIdentifiers:(id)arg1 orderedSizes:(id)arg2 packingOrder:(NSUInteger)arg3 startPosition:(CCUILayoutPoint)arg4 maximumSize:(CCUILayoutSize)arg5 outputLayoutSize:(out CCUILayoutSize*)arg6;
- (instancetype)initWithPackingRules:(id)arg1;
- (CCUILayoutSize)maximumLayoutSize;
- (void)regenerateRectsWithOrderedIdentifiers:(id)arg1 orderedSizes:(id)arg2;
- (CCUILayoutRect)layoutRectForIdentifier:(id)arg1;
@end
