/*
 * This header is generated by classdump-dyld 1.0
 * on Thursday, January 25, 2018 at 11:29:33 PM Eastern European Standard Time
 * Operating System: Version 11.1.2 (Build 15B202)
 * Image Source: /System/Library/PrivateFrameworks/ControlCenterUI.framework/ControlCenterUI
 * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
 */


@protocol UIPreviewInteractionDelegatePrivate <UIPreviewInteractionDelegate>
@optional
- (id)_previewInteractionHighlighterForPreviewTransition:(id)arg1;
- (id)_previewInteraction:(id)arg1 viewControllerPresentationForPresentingViewController:(id)arg2;
- (BOOL)_previewInteractionShouldFinishTransitionToPreview:(id)arg1;
- (BOOL)_previewInteractionShouldAutomaticallyTransitionToPreviewAfterDelay:(id)arg1;
- (id)_previewInteractionViewForHighlight:(id)arg1;
- (id)_previewInteractionViewControllerForPreview:(id)arg1;
- (id)_previewInteraction:(id)arg1 appearanceTransitionForViewController:(id)arg2;
- (id)_previewInteraction:(id)arg1 disappearanceTransitionForViewController:(id)arg2;

@end
